CREATE TABLE `de_to_votox` (
`source` VARCHAR(5) NOT NULL ,
`votox` VARCHAR(5) NOT NULL ,
`comment` VARCHAR(256) NOT NULL DEFAULT ''
) ENGINE = InnoDB;

INSERT INTO `german_to_votox` VALUES
	("1", "S!", "SCH"),
	("2", "oE", "EU"),
	("3", "E", "IE"),
    ("4", "aE", "ei"),
    ("5", "ye", "ö"),
    ("6", "yi", "ü"),
    ("7", "c!jj", "CH"),
    ("A", "u", ""),
    ("Ä", "e", ""),
    ("B", "b", ""),
    ("C", "TS", ""),
    ("D", "d", ""),
    ("E", "e", ""),
    ("F", "f", ""),
    ("G", "g", ""),
    ("H", "h", ""),
    ("I", "E", ""),
    ("J", "y", ""),
    ("K", "K", ""),
    ("L", "l", ""),
    ("M", "m", ""),
    ("N", "n", ""),
    ("O", "o", ""),
    ("Ö", "e", ""),
    ("P", "P", ""),
    ("Q", "Kw", ""),
    ("R", "r", ""),
    ("S", "S", ""),
    ("T", "T", ""),
    ("U", "O", ""),
    ("Ü", "oi", ""),
    ("V", "w", ""),
    ("W", "w", ""),
    ("X", "X", "or KS"),
    ("Y", "y", ""),
    ("Z", "z", "");